version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - redis

  celery-worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
